name: "Node.js Vulnerabilities Cron"
on:
  schedule:
    - cron: "15 14 * * *"

jobs:
  is-my-node-vulnerable:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install
        run: npm install node@20.15.1
      - name: Get node version
        run: node -v
      - name: Install and run is-my-node-vulnerable
        run: npx is-my-node-vulnerable
        
